sudo: false
language: python
git:
  depth: 3
  lfs_skip_smudge: true
  submodules: false
branches:
  only:
    - develop
    - /^v\d+\.\d+\.\d+$/
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.6-dev
  - 3.7-dev
  - 3.8-dev
  - nightly
  - pypy3.5
virtualenv:
  system_site_packages: true
matrix:
  include:
    - python: 3.4
      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py34" COVERAGE="true"
    - env: DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="false"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.5
      python: 3.5
      before_install: pyenv install 3.5.0
  allow_failures:
    - os: osx
    - python: 3.6-dev
    - python: 3.7-dev
    - python: 3.8-dev
    - python: nightly
    - python: pypy3.5
  fast_finish: true
install:
  - source tests/travis_install.sh
script:
  - python setup.py test
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
after_script:
  - travis-cleanup
cache:
  pip: true
  directories:
    - $HOME/miniconda
