sudo: false
language: python
group: travis_latest

git:
  depth: 3
  quiet: true
  submodules: false
  lfs_skip_smudge: true

branches:
  only:
    - develop
    # - /^v\d+\.\d+\.\d+$/
stages:
  - check
  - test
  - deploy

# NOTE: always set to latest stable python version
python: 3.7
# NOTE: always set to latest supported ubuntu version
dist: xenial

cache: pip
install: pip install --upgrade pip setuptools tox tox-travis
script: tox --sitepackages

addons:
  apt:
    update: true
    packages:
      - libgnutls-dev
      - python-pycurl
  homebrew:
    update: true
    packages: python3
  # chocolatey:
    # update: true
    # packages: python3

jobs:
  allow_failures:
    - os:
      - osx
      - windows
    - python: nightly

  include:
    - os: linux
      python: 3.6
    - os: linux
    # - os: linux
      # python: nightly

    # NOTE: work-around to test Python on OSX (officially not supported)
    - os: osx
      language: generic
      env: TOXENV=py37
      before_script:
        pip install virtualenv
        virtualenv -p python3 ~/venv
        source ~/venv/bin/activate

    # NOTE: work-around to test Python on Windows (officially not supported)
    - os: windows
      language: sh
      env: TOXENV=py37
      before_install:
        - cinst -y python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

    - stage: check
      name: Pylint errors
      script: tox -e pylint --sitepackages

    - stage: deploy
      name: Github release
      install:
        - pip install --upgrade pip setuptools wheel
        - pip install -e .[deploy]
      script: false
      deploy:
        provider: releases
        api-key:
          secure: "LDbvOV6EIV2itKUOSQE24RctMJTj7trF8eRQIMQJFa50W/fT03HpHiRVzhddUo4UadzAy5XNm5fRZY5AMNOomQk023mHwTUuPIhQDLVl1Esati7OZpekhKE1v4+sbLfVvvv+rRuDfcn+qjiZ358UU6D4SuZ4zClu6hUxnt0Qc70="
        file_glob: true
        file: dist/*
        skip_cleanup: true
        # prerelease: true
        on:
          repo: pyload/pyload
          branch: develop
          tags: true
    - name: PyPI release
      install:
        - pip install --upgrade pip setuptools wheel
        - pip install -e .[deploy]
      script: false
      deploy:
        provider: pypi
        user:
          secure: "IDWPXbVVMr9/sZOb5/p9bXTvq//EGuzQWM4CnQOm2G4mfaX0ssr7+4w+wweJgI9UJFIcoHmvYC0cjljCleSW1j+1G3GO7whInLUuD63Vt1iA8H4UIvg4JYcTwGZQ9R/PWoW0k5MHems0picgA3cMw/9VBfl3IUraGb6+2QdxpHY="
        password:
          secure: "eoe3SLOEa0Z7UxJI905InCzHatdDigIBt/fl7b6kOHy76IYU3e5lZ/c6urGJBOsy+1LN6vPHvWmVVw/vhevfTd8MM6i0cGXo23zIefYAU2zkjKejWyF2/tke6spngikC1vzEyANs9fNFLXU4USCfgr1lCvuuy9Znwl/sI6jqVTg="
        distributions: release
        skip_cleanup: true
        skip_existing: true
        on:
          repo: pyload/pyload
          branch: develop

matrix:
  fast_finish: true

# after_success:
  # - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
