sudo: false
language: python
git:
  depth: 3
  lfs_skip_smudge: true
  submodules: false
branches:
  only:
    - develop
    # - /^v\d+\.\d+\.\d+$/
python:
  - 3.6
  - 3.7
  - 3.6-dev
  - 3.7-dev
  - 3.8-dev
  - nightly
  # - pypy3.6
virtualenv:
  system_site_packages: true
matrix:
  include:
    - env: DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="false"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.6
      python: 3.6
      before_install: pyenv install 3.6.0
  allow_failures:
    - os: osx
    - python: 3.6-dev
    - python: 3.7-dev
    - python: 3.8-dev
    - python: nightly
    - python: pypy3.5
  fast_finish: true
install:
  - source scripts/travis_install.sh
# script:
  # - python setup.py test
# after_success:
  # - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
after_script:
  - travis-cleanup
cache:
  pip: true
  directories:
    - $HOME/miniconda
deploy:
  provider: pypi
  user: 
    secure: "IDWPXbVVMr9/sZOb5/p9bXTvq//EGuzQWM4CnQOm2G4mfaX0ssr7+4w+wweJgI9UJFIcoHmvYC0cjljCleSW1j+1G3GO7whInLUuD63Vt1iA8H4UIvg4JYcTwGZQ9R/PWoW0k5MHems0picgA3cMw/9VBfl3IUraGb6+2QdxpHY="
  password:
    secure: "eoe3SLOEa0Z7UxJI905InCzHatdDigIBt/fl7b6kOHy76IYU3e5lZ/c6urGJBOsy+1LN6vPHvWmVVw/vhevfTd8MM6i0cGXo23zIefYAU2zkjKejWyF2/tke6spngikC1vzEyANs9fNFLXU4USCfgr1lCvuuy9Znwl/sI6jqVTg="
  distributions: "sdist bdist_wheel"
  on:
    python: 3.6
    branch: develop
